# DTile Tilemap
A library made for handling the data of tilemaps. While first and foremost
developed for DTile, it could just as easily be used for any other project.

## Documentation
Documentation is generated by [ESDoc](https://github.com/esdoc/esdoc).
TODO: Link to documentation.
