window.esdocSearchIndex = [
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "test/tilearea-test.js",
    "test-file/test/tilearea-test.js.html",
    "test/tilearea-test.js",
    "testFile"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber5",
    "tilearea",
    "test"
  ],
  [
    "createtilearea createtilearea,createtilearea",
    "test-file/test/tilearea-test.js.html#lineNumber21",
    "tilearea createTileArea",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber22",
    "tilearea createTileArea requires width and height to equal amount of tiles",
    "test"
  ],
  [
    "filltileareaat filltileareaat,filltileareaat",
    "test-file/test/tilearea-test.js.html#lineNumber163",
    "tilearea fillTileAreaAt",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber196",
    "tilearea fillTileAreaAt doesn't end up in a loop",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber188",
    "tilearea fillTileAreaAt doesn't overwrite anything it shouldn't",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber178",
    "tilearea fillTileAreaAt fills correctly",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber192",
    "tilearea fillTileAreaAt respects tileset ID's",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber183",
    "tilearea fillTileAreaAt tiles correctly",
    "test"
  ],
  [
    "gettile gettile,gettile",
    "test-file/test/tilearea-test.js.html#lineNumber48",
    "tilearea getTile",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber52",
    "tilearea getTile crashes if out of bounds",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber49",
    "tilearea getTile returns the correct tile",
    "test"
  ],
  [
    "gettileareaslice gettileareaslice,gettileareaslice",
    "test-file/test/tilearea-test.js.html#lineNumber63",
    "tilearea getTileAreaSlice",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber82",
    "tilearea getTileAreaSlice crashes if rectangle is invalid",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber78",
    "tilearea getTileAreaSlice returns empty tiles when going out of bounds",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber73",
    "tilearea getTileAreaSlice returns the correct dimmensions",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber64",
    "tilearea getTileAreaSlice returns the correct tiles",
    "test"
  ],
  [
    "tilearea#gettileindex tilearea#gettileindex,tilearea#gettileindex",
    "test-file/test/tilearea-test.js.html#lineNumber32",
    "tilearea getTileIndex",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber37",
    "tilearea getTileIndex crashes if out of bounds",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber33",
    "tilearea getTileIndex returns the right index",
    "test"
  ],
  [
    "gettilingtiledata gettilingtiledata,gettilingtiledata",
    "test-file/test/tilearea-test.js.html#lineNumber93",
    "tilearea getTilingTileData",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber99",
    "tilearea getTilingTileData gets the right tile backwards",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber104",
    "tilearea getTilingTileData gets the right tile far backwards",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber94",
    "tilearea getTilingTileData gets the right tile forward",
    "test"
  ],
  [
    "mergetileareas mergetileareas,mergetileareas",
    "test-file/test/tilearea-test.js.html#lineNumber114",
    "tilearea mergeTileAreas",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber136",
    "tilearea mergeTileAreas can skip empty (-1) tiles",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber146",
    "tilearea mergeTileAreas doesn't crash when going out of bounds",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber128",
    "tilearea mergeTileAreas inserts a tile area correctly",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea-test.js.html#lineNumber155",
    "tilearea mergeTileAreas throws errors like normal",
    "test"
  ]
]