window.esdocSearchIndex = [
  [
    "dtile-tilemap/src/propertyobject.js~propertyobject",
    "class/src/propertyObject.js~PropertyObject.html",
    "<span>PropertyObject</span> <span class=\"search-result-import-path\">dtile-tilemap/src/propertyObject.js</span>",
    "class"
  ],
  [
    "dtile-tilemap/src/tile.js~tile",
    "class/src/tile.js~Tile.html",
    "<span>Tile</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tile.js</span>",
    "class"
  ],
  [
    "dtile-tilemap/src/tilearea.js~tilearea",
    "class/src/tilearea.js~TileArea.html",
    "<span>TileArea</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tilearea.js</span>",
    "class"
  ],
  [
    "dtile-tilemap/src/tilelayer.js~tilelayer",
    "class/src/tilelayer.js~TileLayer.html",
    "<span>TileLayer</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tilelayer.js</span>",
    "class"
  ],
  [
    "dtile-tilemap/src/tilemap.js~tilemap",
    "class/src/tilemap.js~TileMap.html",
    "<span>TileMap</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tilemap.js</span>",
    "class"
  ],
  [
    "dtile-tilemap/src/tileset.js~tileset",
    "class/src/tileset.js~TileSet.html",
    "<span>TileSet</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tileset.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "propertyobject src/propertyobject.js~propertyobject,propertyobject",
    "test-file/test/propertyObject.js.html#lineNumber8",
    "PropertyObject",
    "test"
  ],
  [
    "propertyobject#constructor src/propertyobject.js~propertyobject#constructor,propertyobject#constructor",
    "test-file/test/propertyObject.js.html#lineNumber17",
    "PropertyObject #constructor",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber26",
    "PropertyObject #constructor crashes when passed in an invalid properties object",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber22",
    "PropertyObject #constructor creates from another property object",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber18",
    "PropertyObject #constructor creates width some default values",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber32",
    "PropertyObject #constructor rejects invalid value types",
    "test"
  ],
  [
    "propertyobject#get src/propertyobject.js~propertyobject#get,propertyobject#get",
    "test-file/test/propertyObject.js.html#lineNumber41",
    "PropertyObject #get",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber46",
    "PropertyObject #get crashes when key is not a string",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber42",
    "PropertyObject #get gets basic values correctly",
    "test"
  ],
  [
    "propertyobject#getall src/propertyobject.js~propertyobject#getall,propertyobject#getall",
    "test-file/test/propertyObject.js.html#lineNumber54",
    "PropertyObject #getAll",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber55",
    "PropertyObject #getAll gets all values correctly",
    "test"
  ],
  [
    "propertyobject#set src/propertyobject.js~propertyobject#set,propertyobject#set",
    "test-file/test/propertyObject.js.html#lineNumber71",
    "PropertyObject #set",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber76",
    "PropertyObject #set rejects keys of invalid types",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber81",
    "PropertyObject #set rejects values of invalid types",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber72",
    "PropertyObject #set sets a key correctly",
    "test"
  ],
  [
    "propertyobject#tojson src/propertyobject.js~propertyobject#tojson,propertyobject#tojson",
    "test-file/test/propertyObject.js.html#lineNumber96",
    "PropertyObject #toJSON",
    "test"
  ],
  [
    "",
    "test-file/test/propertyObject.js.html#lineNumber97",
    "PropertyObject #toJSON serializes correctly",
    "test"
  ],
  [
    "tile src/tile.js~tile,tile",
    "test-file/test/tile.js.html#lineNumber8",
    "Tile",
    "test"
  ],
  [
    "tile#clone src/tile.js~tile#clone,tile#clone",
    "test-file/test/tile.js.html#lineNumber79",
    "Tile #clone",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber91",
    "Tile #clone clones all the properties of a tile",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber94",
    "Tile #clone doesn't become the same tile",
    "test"
  ],
  [
    "tile#constructor src/tile.js~tile#constructor,tile#constructor",
    "test-file/test/tile.js.html#lineNumber10",
    "Tile #constructor",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber11",
    "Tile #constructor creates from objects",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber19",
    "Tile #constructor creates from strings",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber24",
    "Tile #constructor has empty default values",
    "test"
  ],
  [
    "tile#settile tile#settile,tile#settile",
    "test-file/test/tile.js.html#lineNumber32",
    "Tile #setTile",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber43",
    "Tile #setTile can replace both tile ID and tileset ID",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber38",
    "Tile #setTile can replace only tile ID",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber53",
    "Tile #setTile does replace empty if told so",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber48",
    "Tile #setTile doesn't replace if ID is -1",
    "test"
  ],
  [
    "tile#tojson src/tile.js~tile#tojson,tile#tojson",
    "test-file/test/tile.js.html#lineNumber61",
    "Tile #toJSON",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber62",
    "Tile #toJSON stringifies with properties",
    "test"
  ],
  [
    "",
    "test-file/test/tile.js.html#lineNumber72",
    "Tile #toJSON stringifies without properties",
    "test"
  ],
  [
    "tilearea src/tilearea.js~tilearea,tilearea",
    "test-file/test/tilearea.js.html#lineNumber8",
    "TileArea",
    "test"
  ],
  [
    "tilearea#constructor src/tilearea.js~tilearea#constructor,tilearea#constructor",
    "test-file/test/tilearea.js.html#lineNumber24",
    "TileArea #constructor",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber25",
    "TileArea #constructor rejects non-tile objects",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber32",
    "TileArea #constructor requires width and height to equal amount of tiles",
    "test"
  ],
  [
    "tilearea#gettilearea src/tilearea.js~tilearea#gettilearea,tilearea#gettilearea",
    "test-file/test/tilearea.js.html#lineNumber57",
    "TileArea #getTileArea",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber72",
    "TileArea #getTileArea crashes if out of bounds",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber80",
    "TileArea #getTileArea crashes if rectangle is invalid",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber67",
    "TileArea #getTileArea returns the correct dimmensions",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber58",
    "TileArea #getTileArea returns the correct tiles",
    "test"
  ],
  [
    "tilearea#gettileindex src/tilearea.js~tilearea#gettileindex,tilearea#gettileindex",
    "test-file/test/tilearea.js.html#lineNumber41",
    "TileArea #getTileIndex",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber46",
    "TileArea #getTileIndex crashes if out of bounds",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber42",
    "TileArea #getTileIndex returns the right index",
    "test"
  ],
  [
    "tilearea#inserttilearea src/tilearea.js~tilearea#inserttilearea,tilearea#inserttilearea",
    "test-file/test/tilearea.js.html#lineNumber91",
    "TileArea #insertTileArea",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber113",
    "TileArea #insertTileArea can skip empty (-1) tiles",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber122",
    "TileArea #insertTileArea doesn't crash when going out of bounds",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber105",
    "TileArea #insertTileArea inserts a tile area correctly",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber133",
    "TileArea TileArea#resize",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber172",
    "TileArea TileArea#resize adds empty tiles when growing",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber156",
    "TileArea TileArea#resize can grow dimmensions",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber151",
    "TileArea TileArea#resize can shrink dimmensions",
    "test"
  ],
  [
    "",
    "test-file/test/tilearea.js.html#lineNumber161",
    "TileArea TileArea#resize keeps tiles intact",
    "test"
  ],
  [
    "tilemap src/tilemap.js~tilemap,tilemap",
    "test-file/test/tilemap.js.html#lineNumber9",
    "TileMap",
    "test"
  ],
  [
    "tilemap#constructor src/tilemap.js~tilemap#constructor,tilemap#constructor",
    "test-file/test/tilemap.js.html#lineNumber33",
    "TileMap #constructor",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber34",
    "TileMap #constructor has a name",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber59",
    "TileMap #constructor has correct default values",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber37",
    "TileMap #constructor has dimmensions",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber48",
    "TileMap #constructor has layers",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber51",
    "TileMap #constructor has properties for layers",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber44",
    "TileMap #constructor has tile size",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber54",
    "TileMap #constructor reads a valid tilemap JSON",
    "test"
  ],
  [
    "tilemap#getjson src/tilemap.js~tilemap#getjson,tilemap#getjson",
    "test-file/test/tilemap.js.html#lineNumber86",
    "TileMap #getJSON",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber90",
    "TileMap #getJSON doesn't parse private properties",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber87",
    "TileMap #getJSON returns a valid JSON string",
    "test"
  ],
  [
    "tilemap#resize src/tilemap.js~tilemap#resize,tilemap#resize",
    "test-file/test/tilemap.js.html#lineNumber67",
    "TileMap #resize",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber77",
    "TileMap #resize changes the size of all layers",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber73",
    "TileMap #resize changes the size of the map",
    "test"
  ],
  [
    "tileset src/tileset.js~tileset,tileset",
    "test-file/test/tileset.js.html#lineNumber8",
    "TileSet",
    "test"
  ],
  [
    "tileset#constructor src/tileset.js~tileset#constructor,tileset#constructor",
    "test-file/test/tileset.js.html#lineNumber10",
    "TileSet #constructor",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber11",
    "TileSet #constructor creates with default values",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber17",
    "TileSet #constructor creates with definded values",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber26",
    "TileSet #constructor fails if any tile properties key isn't a number",
    "test"
  ],
  [
    "tileset#createtileproperties src/tileset.js~tileset#createtileproperties,tileset#createtileproperties",
    "test-file/test/tileset.js.html#lineNumber68",
    "TileSet #createTileProperties",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber69",
    "TileSet #createTileProperties creates a tile property for a tile ID",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber75",
    "TileSet #createTileProperties fails if argument isn't a number",
    "test"
  ],
  [
    "tileset#gettileproperties src/tileset.js~tileset#gettileproperties,tileset#gettileproperties",
    "test-file/test/tileset.js.html#lineNumber37",
    "TileSet #getTileProperty",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber60",
    "TileSet #getTileProperty fails if argument isn't a number",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber49",
    "TileSet #getTileProperty gets a property object correctly",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber54",
    "TileSet #getTileProperty throws an error if ID doesn't have a properties object",
    "test"
  ],
  [
    "tileset#hastileproperties src/tileset.js~tileset#hastileproperties,tileset#hastileproperties",
    "test-file/test/tileset.js.html#lineNumber83",
    "TileSet #hasTileProperties",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber84",
    "TileSet #hasTileProperties checks if there is a tile property object for an ID",
    "test"
  ],
  [
    "",
    "test-file/test/tileset.js.html#lineNumber94",
    "TileSet #hasTileProperties fails if argument isn't a number",
    "test"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/propertyobject.js",
    "file/src/propertyObject.js.html",
    "src/propertyObject.js",
    "file"
  ],
  [
    "src/propertyobject.js~propertyobject#constructor",
    "class/src/propertyObject.js~PropertyObject.html#instance-constructor-constructor",
    "src/propertyObject.js~PropertyObject#constructor",
    "method"
  ],
  [
    "src/propertyobject.js~propertyobject#get",
    "class/src/propertyObject.js~PropertyObject.html#instance-method-get",
    "src/propertyObject.js~PropertyObject#get",
    "method"
  ],
  [
    "src/propertyobject.js~propertyobject#getall",
    "class/src/propertyObject.js~PropertyObject.html#instance-method-getAll",
    "src/propertyObject.js~PropertyObject#getAll",
    "method"
  ],
  [
    "src/propertyobject.js~propertyobject#set",
    "class/src/propertyObject.js~PropertyObject.html#instance-method-set",
    "src/propertyObject.js~PropertyObject#set",
    "method"
  ],
  [
    "src/propertyobject.js~propertyobject#size",
    "class/src/propertyObject.js~PropertyObject.html#instance-get-size",
    "src/propertyObject.js~PropertyObject#size",
    "member"
  ],
  [
    "src/propertyobject.js~propertyobject#tojson",
    "class/src/propertyObject.js~PropertyObject.html#instance-method-toJSON",
    "src/propertyObject.js~PropertyObject#toJSON",
    "method"
  ],
  [
    "src/tile.js",
    "file/src/tile.js.html",
    "src/tile.js",
    "file"
  ],
  [
    "src/tile.js~tile#clone",
    "class/src/tile.js~Tile.html#instance-method-clone",
    "src/tile.js~Tile#clone",
    "method"
  ],
  [
    "src/tile.js~tile#constructor",
    "class/src/tile.js~Tile.html#instance-constructor-constructor",
    "src/tile.js~Tile#constructor",
    "method"
  ],
  [
    "src/tile.js~tile#properties",
    "class/src/tile.js~Tile.html#instance-member-properties",
    "src/tile.js~Tile#properties",
    "member"
  ],
  [
    "src/tile.js~tile#setdata",
    "class/src/tile.js~Tile.html#instance-method-setData",
    "src/tile.js~Tile#setData",
    "method"
  ],
  [
    "src/tile.js~tile#tileid",
    "class/src/tile.js~Tile.html#instance-member-tileId",
    "src/tile.js~Tile#tileId",
    "member"
  ],
  [
    "src/tile.js~tile#tilesetid",
    "class/src/tile.js~Tile.html#instance-member-tilesetId",
    "src/tile.js~Tile#tilesetId",
    "member"
  ],
  [
    "src/tile.js~tile#tojson",
    "class/src/tile.js~Tile.html#instance-method-toJSON",
    "src/tile.js~Tile#toJSON",
    "method"
  ],
  [
    "src/tilearea.js",
    "file/src/tilearea.js.html",
    "src/tilearea.js",
    "file"
  ],
  [
    "src/tilearea.js~tilearea#constructor",
    "class/src/tilearea.js~TileArea.html#instance-constructor-constructor",
    "src/tilearea.js~TileArea#constructor",
    "method"
  ],
  [
    "src/tilearea.js~tilearea#gettilearea",
    "class/src/tilearea.js~TileArea.html#instance-method-getTileArea",
    "src/tilearea.js~TileArea#getTileArea",
    "method"
  ],
  [
    "src/tilearea.js~tilearea#gettileindex",
    "class/src/tilearea.js~TileArea.html#instance-method-getTileIndex",
    "src/tilearea.js~TileArea#getTileIndex",
    "method"
  ],
  [
    "src/tilearea.js~tilearea#height",
    "class/src/tilearea.js~TileArea.html#instance-member-height",
    "src/tilearea.js~TileArea#height",
    "member"
  ],
  [
    "src/tilearea.js~tilearea#inserttilearea",
    "class/src/tilearea.js~TileArea.html#instance-method-insertTileArea",
    "src/tilearea.js~TileArea#insertTileArea",
    "method"
  ],
  [
    "src/tilearea.js~tilearea#resize",
    "class/src/tilearea.js~TileArea.html#instance-method-resize",
    "src/tilearea.js~TileArea#resize",
    "method"
  ],
  [
    "src/tilearea.js~tilearea#tiles",
    "class/src/tilearea.js~TileArea.html#instance-member-tiles",
    "src/tilearea.js~TileArea#tiles",
    "member"
  ],
  [
    "src/tilearea.js~tilearea#width",
    "class/src/tilearea.js~TileArea.html#instance-member-width",
    "src/tilearea.js~TileArea#width",
    "member"
  ],
  [
    "src/tilelayer.js",
    "file/src/tilelayer.js.html",
    "src/tilelayer.js",
    "file"
  ],
  [
    "src/tilelayer.js~tilelayer#constructor",
    "class/src/tilelayer.js~TileLayer.html#instance-constructor-constructor",
    "src/tilelayer.js~TileLayer#constructor",
    "method"
  ],
  [
    "src/tilelayer.js~tilelayer#name",
    "class/src/tilelayer.js~TileLayer.html#instance-member-name",
    "src/tilelayer.js~TileLayer#name",
    "member"
  ],
  [
    "src/tilelayer.js~tilelayer#properties",
    "class/src/tilelayer.js~TileLayer.html#instance-member-properties",
    "src/tilelayer.js~TileLayer#properties",
    "member"
  ],
  [
    "src/tilemap.js",
    "file/src/tilemap.js.html",
    "src/tilemap.js",
    "file"
  ],
  [
    "src/tilemap.js~tilemap#addtileset",
    "class/src/tilemap.js~TileMap.html#instance-method-addTileset",
    "src/tilemap.js~TileMap#addTileset",
    "method"
  ],
  [
    "src/tilemap.js~tilemap#constructor",
    "class/src/tilemap.js~TileMap.html#instance-constructor-constructor",
    "src/tilemap.js~TileMap#constructor",
    "method"
  ],
  [
    "src/tilemap.js~tilemap#createlayer",
    "class/src/tilemap.js~TileMap.html#instance-method-createLayer",
    "src/tilemap.js~TileMap#createLayer",
    "method"
  ],
  [
    "src/tilemap.js~tilemap#getjson",
    "class/src/tilemap.js~TileMap.html#instance-method-getJSON",
    "src/tilemap.js~TileMap#getJSON",
    "method"
  ],
  [
    "src/tilemap.js~tilemap#height",
    "class/src/tilemap.js~TileMap.html#instance-get-height",
    "src/tilemap.js~TileMap#height",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#layers",
    "class/src/tilemap.js~TileMap.html#instance-member-layers",
    "src/tilemap.js~TileMap#layers",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#name",
    "class/src/tilemap.js~TileMap.html#instance-member-name",
    "src/tilemap.js~TileMap#name",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#properties",
    "class/src/tilemap.js~TileMap.html#instance-member-properties",
    "src/tilemap.js~TileMap#properties",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#resize",
    "class/src/tilemap.js~TileMap.html#instance-method-resize",
    "src/tilemap.js~TileMap#resize",
    "method"
  ],
  [
    "src/tilemap.js~tilemap#tileheight",
    "class/src/tilemap.js~TileMap.html#instance-member-tileHeight",
    "src/tilemap.js~TileMap#tileHeight",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#tilewidth",
    "class/src/tilemap.js~TileMap.html#instance-member-tileWidth",
    "src/tilemap.js~TileMap#tileWidth",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#tilesets",
    "class/src/tilemap.js~TileMap.html#instance-member-tilesets",
    "src/tilemap.js~TileMap#tilesets",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#width",
    "class/src/tilemap.js~TileMap.html#instance-get-width",
    "src/tilemap.js~TileMap#width",
    "member"
  ],
  [
    "src/tileset.js",
    "file/src/tileset.js.html",
    "src/tileset.js",
    "file"
  ],
  [
    "src/tileset.js~tileset#constructor",
    "class/src/tileset.js~TileSet.html#instance-constructor-constructor",
    "src/tileset.js~TileSet#constructor",
    "method"
  ],
  [
    "src/tileset.js~tileset#createtileproperties",
    "class/src/tileset.js~TileSet.html#instance-method-createTileProperties",
    "src/tileset.js~TileSet#createTileProperties",
    "method"
  ],
  [
    "src/tileset.js~tileset#gettileproperties",
    "class/src/tileset.js~TileSet.html#instance-method-getTileProperties",
    "src/tileset.js~TileSet#getTileProperties",
    "method"
  ],
  [
    "src/tileset.js~tileset#hastileproperties",
    "class/src/tileset.js~TileSet.html#instance-method-hasTileProperties",
    "src/tileset.js~TileSet#hasTileProperties",
    "method"
  ],
  [
    "src/tileset.js~tileset#name",
    "class/src/tileset.js~TileSet.html#instance-member-name",
    "src/tileset.js~TileSet#name",
    "member"
  ],
  [
    "src/tileset.js~tileset#path",
    "class/src/tileset.js~TileSet.html#instance-member-path",
    "src/tileset.js~TileSet#path",
    "member"
  ],
  [
    "src/tileset.js~tileset#properties",
    "class/src/tileset.js~TileSet.html#instance-member-properties",
    "src/tileset.js~TileSet#properties",
    "member"
  ],
  [
    "src/tileset.js~tileset#type",
    "class/src/tileset.js~TileSet.html#instance-member-type",
    "src/tileset.js~TileSet#type",
    "member"
  ],
  [
    "test/propertyobject.js",
    "test-file/test/propertyObject.js.html",
    "test/propertyObject.js",
    "testFile"
  ],
  [
    "test/tile.js",
    "test-file/test/tile.js.html",
    "test/tile.js",
    "testFile"
  ],
  [
    "test/tilearea.js",
    "test-file/test/tilearea.js.html",
    "test/tilearea.js",
    "testFile"
  ],
  [
    "test/tilemap.js",
    "test-file/test/tilemap.js.html",
    "test/tilemap.js",
    "testFile"
  ],
  [
    "test/tileset.js",
    "test-file/test/tileset.js.html",
    "test/tileset.js",
    "testFile"
  ]
]