window.esdocSearchIndex = [
  [
    "dtile-tilemap/src/tile.js~tile",
    "class/src/tile.js~Tile.html",
    "<span>Tile</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tile.js</span>",
    "class"
  ],
  [
    "dtile-tilemap/src/tilelayer.js~tilelayer",
    "class/src/tilelayer.js~TileLayer.html",
    "<span>TileLayer</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tilelayer.js</span>",
    "class"
  ],
  [
    "dtile-tilemap/src/tilemap.js~tilemap",
    "class/src/tilemap.js~TileMap.html",
    "<span>TileMap</span> <span class=\"search-result-import-path\">dtile-tilemap/src/tilemap.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "tilemap src/tilemap.js~tilemap,tilemap",
    "test-file/test/tilemap.js.html#lineNumber10",
    "TileMap",
    "test"
  ],
  [
    "tilemap#constructor src/tilemap.js~tilemap#constructor,tilemap#constructor",
    "test-file/test/tilemap.js.html#lineNumber34",
    "TileMap #create",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber35",
    "TileMap #create has a name",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber38",
    "TileMap #create has dimmensions",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber49",
    "TileMap #create has layers",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber52",
    "TileMap #create has properties for layers",
    "test"
  ],
  [
    "",
    "test-file/test/tilemap.js.html#lineNumber45",
    "TileMap #create has tile size",
    "test"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/tile.js",
    "file/src/tile.js.html",
    "src/tile.js",
    "file"
  ],
  [
    "src/tile.js~tile#constructor",
    "class/src/tile.js~Tile.html#instance-constructor-constructor",
    "src/tile.js~Tile#constructor",
    "method"
  ],
  [
    "src/tile.js~tile#properties",
    "class/src/tile.js~Tile.html#instance-member-properties",
    "src/tile.js~Tile#properties",
    "member"
  ],
  [
    "src/tile.js~tile#tileid",
    "class/src/tile.js~Tile.html#instance-member-tileId",
    "src/tile.js~Tile#tileId",
    "member"
  ],
  [
    "src/tile.js~tile#tilesetid",
    "class/src/tile.js~Tile.html#instance-member-tilesetId",
    "src/tile.js~Tile#tilesetId",
    "member"
  ],
  [
    "src/tilelayer.js",
    "file/src/tilelayer.js.html",
    "src/tilelayer.js",
    "file"
  ],
  [
    "src/tilelayer.js~tilelayer#constructor",
    "class/src/tilelayer.js~TileLayer.html#instance-constructor-constructor",
    "src/tilelayer.js~TileLayer#constructor",
    "method"
  ],
  [
    "src/tilelayer.js~tilelayer#name",
    "class/src/tilelayer.js~TileLayer.html#instance-member-name",
    "src/tilelayer.js~TileLayer#name",
    "member"
  ],
  [
    "src/tilelayer.js~tilelayer#properties",
    "class/src/tilelayer.js~TileLayer.html#instance-member-properties",
    "src/tilelayer.js~TileLayer#properties",
    "member"
  ],
  [
    "src/tilelayer.js~tilelayer#tiles",
    "class/src/tilelayer.js~TileLayer.html#instance-member-tiles",
    "src/tilelayer.js~TileLayer#tiles",
    "member"
  ],
  [
    "src/tilemap.js",
    "file/src/tilemap.js.html",
    "src/tilemap.js",
    "file"
  ],
  [
    "src/tilemap.js~tilemap#constructor",
    "class/src/tilemap.js~TileMap.html#instance-constructor-constructor",
    "src/tilemap.js~TileMap#constructor",
    "method"
  ],
  [
    "src/tilemap.js~tilemap#createlayer",
    "class/src/tilemap.js~TileMap.html#instance-method-createLayer",
    "src/tilemap.js~TileMap#createLayer",
    "method"
  ],
  [
    "src/tilemap.js~tilemap#height",
    "class/src/tilemap.js~TileMap.html#instance-member-height",
    "src/tilemap.js~TileMap#height",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#layers",
    "class/src/tilemap.js~TileMap.html#instance-member-layers",
    "src/tilemap.js~TileMap#layers",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#name",
    "class/src/tilemap.js~TileMap.html#instance-member-name",
    "src/tilemap.js~TileMap#name",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#properties",
    "class/src/tilemap.js~TileMap.html#instance-member-properties",
    "src/tilemap.js~TileMap#properties",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#tileheight",
    "class/src/tilemap.js~TileMap.html#instance-member-tileHeight",
    "src/tilemap.js~TileMap#tileHeight",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#tilewidth",
    "class/src/tilemap.js~TileMap.html#instance-member-tileWidth",
    "src/tilemap.js~TileMap#tileWidth",
    "member"
  ],
  [
    "src/tilemap.js~tilemap#width",
    "class/src/tilemap.js~TileMap.html#instance-member-width",
    "src/tilemap.js~TileMap#width",
    "member"
  ],
  [
    "test/tilemap.js",
    "test-file/test/tilemap.js.html",
    "test/tilemap.js",
    "testFile"
  ]
]